services:
  gitlab-runner:
    image: 'gitlab/gitlab-runner:v17.5.2'
    container_name: gitlab-runner
    volumes:
      - '/etc/gitlab-runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
