version: '3.3'
services:
  alkis:
    image: '${IMAGE_HOST}/vendor/archikart-alkis:latest'
    ports:
      - ${MAIN_PORT}:22
    networks:
      - alkis-net
    volumes:
      - alkis-filestore:/root/archikart/alkis/filestore
    depends_on:
      - postgis
    restart: unless-stopped
    links:
      - 'postgis:archikart-postgis'
  postgis:
    image: '${IMAGE_HOST}/vendor/archikart-postgis:latest'
    ports:
      - ${DB_PORT}:5432
    networks:
      - alkis-net
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: archikart
    restart: unless-stopped
    shm_size: '6gb'
volumes:
  alkis-filestore: {}
  pg-data: {}
networks:
  alkis-net: {}
