services:
  alkis:
    image: 'docker.archikart.de/archikart/alkis_gid7_v78:latest'
    container_name: alkis
    ports:
      - ${MAIN_PORT}:22
    networks:
      - alkis-net
    volumes:
      - alkis-filestore:/root/archikart/alkis/filestore
    depends_on:
      - postgis
    restart: unless-stopped
    links:
      - 'postgis:archikart-postgis'
  postgis:
    image: 'docker.archikart.de/archikart/alkis_postgis_v78:latest'
    container_name: postgis
    ports:
      - ${DB_PORT}:5432
    networks:
      - alkis-net
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: archikart
    restart: unless-stopped
    shm_size: '6gb'
volumes:
  alkis-filestore: {}
  pg-data: {}
networks:
  alkis-net: {}
